### ISSUE TITLE
NCM2 or Coc for PHP

### ISSUE THREAD

**Issue by gour** [MattCne/terminal_config#2]
Hello,

I read your fantastic [Vim for PHP](https://thevaluable.dev/vim-php-ide/) post which is very helpful for someone wanting to write some PHP and using (neo)vim since I've decided to abandon Emacs...

Now, by looking at your config I see that you replaced NCM2 with Coc and wonder whether you recommend the same for someone in need to write PHP (along with HTML/CSS/JS) and Markdown, but not intending to go into Golang (wanted to use Hugo or some other static-site-generator, but chosen Tiki CMS instead).?

There is also Deoplete...in any case, I plan to mostly use Neovim...

**Comment by Phantas0s** [comment]
Hello gour,

Thanks for the kind words!

I would not recommend to use `coc.vim` for PHP/HTML/CSS, since it add quite some overhead and is not fully compatible with the fantastic `phpactor`. It's not that stable either,

NCM2 is easier to configure than Deoplete in my experience.

Hope it helps!

**Comment by gour** [comment]
>  I would not recommend to use coc.vim for PHP/HTML/CSS

And what about using Go (in the begginning Go-templates...for working with Hugo)?

**Comment by gour** [comment]
>  Hope it helps!

Btw, thanks to your site I've discovered [GMB](https://gmb.io/) which looks very cool. ;)

**Comment by Phantas0s** [comment]
You don't need it for Go either. You can try [vim-go](https://github.com/fatih/vim-go) for Go templates syntax highlighting. Go templates are pretty simple. 

You're welcome for GMB!

**Comment by gour** [comment]
> You don't need it for Go either. You can try vim-go for Go templates syntax highlighting. 

Thanks!

> Go templates are pretty simple.

OK.

> You're welcome for GMB!

:-)
