### ISSUE TITLE
Gdiff dont work 

### ISSUE THREAD

**Issue by hneis** [MattCne/terminal_config#5]
Gdif don't work in php files, if enabled this plugin 
`Plug 'dbeniamine/cheat.sh-vim'`

https://github.com/Phantas0s/.dotfiles/blob/d4f1e440581c004b7d03e2c337b81fc8034ebe0c/nvim/init.vim#L152

**Comment by Phantas0s** [comment]
Interesting. Thanks for letting me know! I never use the plugin anyway so I deleted it.
