### ISSUE TITLE
Vi cursor mode: support for Home and End keys

### ISSUE THREAD

**Issue by ashwinvis** [MattCne/terminal_config#6]
Having a simple zle-line-init breaks <kbd>Home</kbd> and <kbd>End</kbd> keys. See https://github.com/ohmyzsh/ohmyzsh/issues/3061#issuecomment-149108390

```sh
    zle-line-init() {
        printf $cursor_beam
        #  OR...
        zle -K viins
        # OR having a blank zle-line-init breaks Home and End
    }
```
I modified the output of `which zle-line-init` and that seems to work:

```sh   
    zle-line-init () {
        # Default zle-line-init
        if (( $+terminfo[smkx] ))
        then
                echoti smkx
        fi
        zle editor-info

        # Modify cursor!
        zle -K viins
    }
```

EDIT: For some context, I am using Prezto with `bindkey -v` and merely added your cursor_mode plugin

**Comment by Phantas0s** [comment]
Nice! Thanks for that!
