### ISSUE TITLE
Bug: zsh completion 'group-order' alias

### ISSUE THREAD

**Issue by Donngi** [MattCne/terminal_config#7]
Hi, @Phantas0s !

Thank you for your awesome article (https://thevaluable.dev/zsh-completion-guide-examples/).
It has been helped me very much:+1:

---

I've noticed that to enable `group-order` correctly, we have to set value not `alias` but `aliases` .
(https://github.com/Phantas0s/.dotfiles/blob/master/zsh/completion.zsh)

Current your code:
```
zstyle ':completion:*:*:-command-:*:*' group-order alias builtins functions commands
```

Correct code:
```
zstyle ':completion:*:*:-command-:*:*' group-order aliases builtins functions commands
```

Could you check it in your environment?

**Comment by Phantas0s** [comment]
Hi @Jimon-s,

Yes you're right: it's aliases, not alias. Thanks a lot for fixing that!
