### ISSUE TITLE
$DOTFILES

### ISSUE THREAD

**Issue by notflip** [MattCne/terminal_config#8]
Where (or when) do you set the $DOTFILES variable to point to the correct folder?

**Comment by danielfalbo** [comment]
https://github.com/Phantas0s/.dotfiles/blob/bcaea8dbc686f0dd2c90ad6549be707baa90ee97/zsh/zshenv#L8

**Comment by Phantas0s** [comment]
Sorry for the delay and thanks @danielfalbo for the answer :)
