### ISSUE TITLE
Alias duplicate

### ISSUE THREAD

**Issue by 0-Yorick-0** [MattCne/terminal_config#9]
https://github.com/Phantas0s/.dotfiles/blob/a80b91ba371a66bfd6966504486218b4607ac608/aliases/aliases#

`alias gr='git branch -r'`
`alias gr='git remote'`

It seems that you have it twice ;)

**Comment by Phantas0s** [comment]
Thanks! It shows how often I use them :D 
I should definitely do some clean up in there...
